version: 0.2

phases:
  pre_build:
    commands:
      - sudo apt update
      - sudo apt install -y apache2 php libapache2-mod-php php-mysql php-dom php-gd mysql-server git
  build:
    commands:
      - # Add your build commands here
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - "**/*"
  discard-paths: no